version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:03:05:60:a4:2e:5b:04:e6:4e:46:23:45:66:70:bd"
      - run:
          name: Deploy Master to Dokku
          command: |
            git push $DOKKU_GIT_ENDPOINT master

workflows:
  version: 2
  deploy_middleman:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
