version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy Master to Dokku
          command: |
            yes yes | git push $DOKKU_GIT_ENDPOINT master

workflows:
  version: 2
  deploy_middleman:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
