version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
           name: Add DOKKU_SERVER_IP to known_hosts
           command: ssh-keyscan -H $DOKKU_SERVER_IP >> ~/.ssh/known_hosts
      - run:
          name: Deploy Master to Dokku
          command: |
            git push $DOKKU_GIT_ENDPOINT master

workflows:
  version: 2
  deploy_middleman:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
