version: 2
jobs:
  deploy:
    machine:
        enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy Master to Dokku
          command: |
            git push $DOKKU_GIT_ENDPOINT master

workflows:
  version: 2
  deploy_middleman:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
